services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - database/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-network
    restart: always
    ports:
      - "5432:5432"

  back:
    platform: linux/amd64
    build: ./apps/back
    image: seminar-back-image
    container_name: back
    env_file:
      - apps/back/.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - back-network
    volumes:
      - ./apps/back/src:/app/src
    restart: always

  front:
    build: ./apps/front
    image: seminar-front-image
    container_name: front
    env_file:
      - apps/front/.env
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - back-network
    volumes:
      - ./apps/front/src:/app/src
      - ./apps/front/public:/app/public
    restart: always

volumes:
  db-data:

networks:
  back-network:
