import { AstrologicalSign, Compatibility } from "../types";

export const compatibilityScores: {
  [key in AstrologicalSign]: {
    [key in AstrologicalSign]: Compatibility;
  };
} = {
  Aries: {
    Aries: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 2,
      Communication: 3,
      score: 65,
    },
    Taurus: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 2,
      Communication: 1,
      score: 35,
    },
    Gemini: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 4,
      score: 80,
    },
    Cancer: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 2,
      Communication: 2,
      score: 40,
    },
    Leo: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 90,
    },
    Virgo: {
      Overall: 3,
      Sex: 2,
      "Love & Mariage": 3,
      Communication: 4,
      score: 60,
    },
    Libra: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 3,
      score: 80,
    },
    Scorpio: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 3,
      score: 60,
    },
    Sagittarius: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Capricorn: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 3,
      score: 60,
    },
    Aquarius: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 4,
      score: 80,
    },
    Pisces: {
      Overall: 2,
      Sex: 3,
      "Love & Mariage": 1,
      Communication: 2,
      score: 40,
    },
  },
  Taurus: {
    Aries: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 2,
      Communication: 1,
      score: 35,
    },
    Taurus: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 2,
      Communication: 3,
      score: 60,
    },
    Gemini: {
      Overall: 2,
      Sex: 3,
      "Love & Mariage": 1,
      Communication: 1,
      score: 35,
    },
    Cancer: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Leo: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Virgo: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Libra: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Scorpio: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Sagittarius: {
      Overall: 1,
      Sex: 1,
      "Love & Mariage": 1,
      Communication: 2,
      score: 25,
    },
    Capricorn: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Aquarius: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 3,
      score: 60,
    },
    Pisces: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
  },
  Gemini: {
    Aries: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 4,
      score: 80,
    },
    Taurus: {
      Overall: 2,
      Sex: 3,
      "Love & Mariage": 1,
      Communication: 1,
      score: 35,
    },
    Gemini: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 4,
      score: 70,
    },
    Cancer: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Leo: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 5,
      score: 95,
    },
    Virgo: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 4,
      score: 65,
    },
    Libra: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Scorpio: {
      Overall: 1,
      Sex: 2,
      "Love & Mariage": 1,
      Communication: 1,
      score: 25,
    },
    Sagittarius: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Capricorn: {
      Overall: 4,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 4,
      score: 70,
    },
    Aquarius: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Pisces: {
      Overall: 2,
      Sex: 4,
      "Love & Mariage": 2,
      Communication: 2,
      score: 50,
    },
  },
  Cancer: {
    Aries: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 2,
      Communication: 2,
      score: 40,
    },
    Taurus: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Gemini: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Cancer: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 4,
      score: 80,
    },
    Leo: {
      Overall: 2,
      Sex: 1,
      "Love & Mariage": 3,
      Communication: 2,
      score: 40,
    },
    Virgo: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 5,
      score: 85,
    },
    Libra: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 2,
      score: 60,
    },
    Scorpio: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 5,
      score: 95,
    },
    Sagittarius: {
      Overall: 3,
      Sex: 2,
      "Love & Mariage": 3,
      Communication: 3,
      score: 55,
    },
    Capricorn: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Aquarius: {
      Overall: 1,
      Sex: 1,
      "Love & Mariage": 2,
      Communication: 2,
      score: 30,
    },
    Pisces: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
  },
  Leo: {
    Aries: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Taurus: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Gemini: {
      Overall: 5,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 5,
      score: 90,
    },
    Cancer: {
      Overall: 2,
      Sex: 1,
      "Love & Mariage": 3,
      Communication: 2,
      score: 40,
    },
    Leo: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 3,
      score: 60,
    },
    Virgo: {
      Overall: 2,
      Sex: 1,
      "Love & Mariage": 3,
      Communication: 3,
      score: 45,
    },
    Libra: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Scorpio: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Sagittarius: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Capricorn: {
      Overall: 2,
      Sex: 3,
      "Love & Mariage": 2,
      Communication: 2,
      score: 45,
    },
    Aquarius: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 3,
      score: 75,
    },
    Pisces: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 2,
      score: 55,
    },
  },
  Virgo: {
    Aries: {
      Overall: 3,
      Sex: 2,
      "Love & Mariage": 3,
      Communication: 4,
      score: 60,
    },
    Taurus: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Gemini: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 4,
      score: 65,
    },
    Cancer: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 5,
      score: 85,
    },
    Leo: {
      Overall: 2,
      Sex: 1,
      "Love & Mariage": 3,
      Communication: 3,
      score: 45,
    },
    Virgo: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 4,
      score: 65,
    },
    Libra: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 4,
      score: 65,
    },
    Scorpio: {
      Overall: 4,
      Sex: 3,
      "Love & Mariage": 4,
      Communication: 5,
      score: 80,
    },
    Sagittarius: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 2,
      score: 60,
    },
    Capricorn: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Aquarius: {
      Overall: 2,
      Sex: 1,
      "Love & Mariage": 2,
      Communication: 2,
      score: 35,
    },
    Pisces: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
  },
  Libra: {
    Aries: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 3,
      score: 80,
    },
    Taurus: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Gemini: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Cancer: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 2,
      score: 60,
    },
    Leo: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Virgo: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 4,
      score: 65,
    },
    Libra: {
      Overall: 4,
      Sex: 3,
      "Love & Mariage": 4,
      Communication: 4,
      score: 75,
    },
    Scorpio: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 2,
      Communication: 1,
      score: 35,
    },
    Sagittarius: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 3,
      score: 80,
    },
    Capricorn: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Aquarius: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Pisces: {
      Overall: 2,
      Sex: 3,
      "Love & Mariage": 1,
      Communication: 2,
      score: 40,
    },
  },
  Scorpio: {
    Aries: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 3,
      score: 60,
    },
    Taurus: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Gemini: {
      Overall: 1,
      Sex: 2,
      "Love & Mariage": 1,
      Communication: 1,
      score: 25,
    },
    Cancer: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Leo: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Virgo: {
      Overall: 4,
      Sex: 3,
      "Love & Mariage": 4,
      Communication: 5,
      score: 80,
    },
    Libra: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 2,
      Communication: 1,
      score: 35,
    },
    Scorpio: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Sagittarius: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 2,
      Communication: 1,
      score: 35,
    },
    Capricorn: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Aquarius: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 4,
      score: 80,
    },
    Pisces: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
  },
  Sagittarius: {
    Aries: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Taurus: {
      Overall: 1,
      Sex: 1,
      "Love & Mariage": 1,
      Communication: 2,
      score: 25,
    },
    Gemini: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Cancer: {
      Overall: 3,
      Sex: 2,
      "Love & Mariage": 3,
      Communication: 3,
      score: 55,
    },
    Leo: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Virgo: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 2,
      score: 60,
    },
    Libra: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 3,
      score: 80,
    },
    Scorpio: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 2,
      Communication: 1,
      score: 35,
    },
    Sagittarius: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Capricorn: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Aquarius: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 5,
      score: 95,
    },
    Pisces: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
  },
  Capricorn: {
    Aries: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 3,
      score: 60,
    },
    Taurus: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Gemini: {
      Overall: 4,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 4,
      score: 70,
    },
    Cancer: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Leo: {
      Overall: 2,
      Sex: 3,
      "Love & Mariage": 2,
      Communication: 2,
      score: 45,
    },
    Virgo: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Libra: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Scorpio: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Sagittarius: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Capricorn: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Aquarius: {
      Overall: 1,
      Sex: 1,
      "Love & Mariage": 2,
      Communication: 2,
      score: 30,
    },
    Pisces: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
  },
  Aquarius: {
    Aries: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 4,
      score: 80,
    },
    Taurus: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 3,
      score: 60,
    },
    Gemini: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Cancer: {
      Overall: 1,
      Sex: 1,
      "Love & Mariage": 2,
      Communication: 2,
      score: 30,
    },
    Leo: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 3,
      score: 75,
    },
    Virgo: {
      Overall: 2,
      Sex: 1,
      "Love & Mariage": 2,
      Communication: 2,
      score: 35,
    },
    Libra: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Scorpio: {
      Overall: 4,
      Sex: 4,
      "Love & Mariage": 4,
      Communication: 4,
      score: 80,
    },
    Sagittarius: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 5,
      score: 95,
    },
    Capricorn: {
      Overall: 1,
      Sex: 1,
      "Love & Mariage": 2,
      Communication: 2,
      score: 30,
    },
    Aquarius: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 3,
      score: 60,
    },
    Pisces: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 3,
      Communication: 2,
      score: 45,
    },
  },
  Pisces: {
    Aries: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Taurus: {
      Overall: 2,
      Sex: 4,
      "Love & Mariage": 2,
      Communication: 2,
      score: 50,
    },
    Gemini: {
      Overall: 2,
      Sex: 4,
      "Love & Mariage": 2,
      Communication: 2,
      score: 50,
    },
    Cancer: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Leo: {
      Overall: 3,
      Sex: 3,
      "Love & Mariage": 3,
      Communication: 2,
      score: 55,
    },
    Virgo: {
      Overall: 4,
      Sex: 5,
      "Love & Mariage": 4,
      Communication: 4,
      score: 85,
    },
    Libra: {
      Overall: 2,
      Sex: 3,
      "Love & Mariage": 1,
      Communication: 2,
      score: 40,
    },
    Scorpio: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Sagittarius: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
    Capricorn: {
      Overall: 5,
      Sex: 5,
      "Love & Mariage": 5,
      Communication: 5,
      score: 100,
    },
    Aquarius: {
      Overall: 2,
      Sex: 2,
      "Love & Mariage": 3,
      Communication: 2,
      score: 45,
    },
    Pisces: {
      Overall: 3,
      Sex: 4,
      "Love & Mariage": 3,
      Communication: 3,
      score: 65,
    },
  },
};
